
vscode:
  extensions:
    - vscodevim.vim
tasks:
  - before: >
    mkdir -p ~/.ssh &&
    [[ ! -z $SSH_PUBLIC_KEY  ]] &&
    echo $SSH_PUBLIC_KEY > ~/.ssh/id_ed25519.pub &&
    chmod 644 ~/.ssh/id_ed25519.pub &&
    [[ ! -z $SSH_PRIVATE_KEY  ]] &&
    echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_ed25519 &&
    chmod 600 ~/.ssh/id_ed25519
  - before: git config --global user.email $USER_EMAIL
